export class Grid {

    constructor(
        public g1: string, 
        public g2: string, 
        public g3: string, 
        public g4: string, 
        public g5: string, 
        public g6: string, 
        public g7: string, 
        public g8: string, 
        public g9: string, 
        public g10: string,
        public g11: string,
        public g12: string,
        public g13: string,
        public g14: string,
        public g15: string,
        public g16: string,
        public g17: string,
        public g18: string,
        public g19: string,
        public g20: string,
        public g21: string,
        public g22: string,
        public g23: string,
        public g24: string,
        public g25: string,
        public g26: string,
        public g27: string,
        public g28: string,
        public g29: string,
        public g30: string,
        public g31: string,
        public g32: string,
        public g33: string,
        public g34: string,
        public g35: string,
        public g36: string,
      
        public isg1Disabled: boolean,
        public isg2Disabled: boolean,
        public isg3Disabled: boolean,
        public isg4Disabled: boolean,
        public isg5Disabled: boolean,
        public isg6Disabled: boolean,
        public isg7Disabled: boolean,
        public isg8Disabled: boolean,
        public isg9Disabled: boolean,
        public isg10Disabled: boolean,
        public isg11Disabled: boolean,
        public isg12Disabled: boolean,
        public isg13Disabled: boolean,
        public isg14Disabled: boolean,
        public isg15Disabled: boolean,
        public isg16Disabled: boolean,
        public isg17Disabled: boolean,
        public isg18Disabled: boolean,
        public isg19Disabled: boolean,
        public isg20Disabled: boolean,
        public isg21Disabled: boolean,
        public isg22Disabled: boolean,
        public isg23Disabled: boolean,
        public isg24Disabled: boolean,
        public isg25Disabled: boolean,
        public isg26Disabled: boolean,
        public isg27Disabled: boolean,
        public isg28Disabled: boolean,
        public isg29Disabled: boolean,
        public isg30Disabled: boolean,
        public isg31Disabled: boolean,
        public isg32Disabled: boolean,
        public isg33Disabled: boolean,
        public isg34Disabled: boolean,
        public isg35Disabled: boolean,
        public isg36Disabled: boolean
      )
       {

        }

}
